from enum import Enum


class HitDirection(str, Enum):
    CENTER = "CENTER"
    LEFT = "LEFT"
    RIGHT = "RIGHT"
    UP = "UP"
    DOWN = "DOWN"
    UP_LEFT = "UP_LEFT"
    UP_RIGHT = "UP_RIGHT"
    DOWN_LEFT = "DOWN_LEFT"
    DOWN_RIGHT = "DOWN_RIGHT"
    MISS = "MISS"
    INVALID = "INVALID"


class SystemState(str, Enum):
    CALIBRATING = "CALIBRATING"
    READY = "READY"
    ENABLING_COMPLIANCE = "ENABLING_COMPLIANCE"
    STABILIZING_COMPLIANCE = "STABILIZING_COMPLIANCE"
    WAITING_FOR_HIT = "WAITING_FOR_HIT"
    ANALYZING = "ANALYZING"
    RETURNING_TO_REFERENCE = "RETURNING_TO_REFERENCE"
    TEST_COMPLETE = "TEST_COMPLETE"
    STOPPING = "STOPPING"
    ERROR = "ERROR"
