<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mitt_hit_bringup</name>
  <version>0.1.0</version>
  <description>Launch and integration configuration for the mitt hit system.</description>
  <maintainer email="rokey@todo.local">rokey</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>mitt_hit_system</exec_depend>
  <exec_depend>boxing_integration</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
